from elearn.models import Categorie, SousCategorie

def addCate():
    categorie1 = Categorie(nom='Arts et humanités')
    categorie1.save()
    categorie2 = Categorie(nom='Business')
    categorie2.save()
    categorie3 = Categorie(nom='Informatique')
    categorie3.save()
    categorie4 = Categorie(nom='Science des données')
    categorie4.save()
    categorie5 = Categorie(nom='Sciences de la vie')
    categorie5.save()
    categorie6 = Categorie(nom='Mathématiques et logique')
    categorie6.save()
    categorie7 = Categorie(nom='Développement personnel')
    categorie7.save()
    categorie8 = Categorie(nom='Sciences physiques et ingénierie')
    categorie8.save()
    categorie9 = Categorie(nom='Sciences sociales')
    categorie9.save()
    categorie10 = Categorie(nom='Apprentissage des langues')
    categorie10.save()

    sousCate11 = SousCategorie(nom='Musique et art', categorie=categorie1)
    sousCate11.save()
    sousCate12 = SousCategorie(nom='Histoire', categorie=categorie1)
    sousCate12.save()
    sousCate13 = SousCategorie(nom='Philosophie', categorie=categorie1)
    sousCate13.save()

    sousCate21 = SousCategorie(nom='Leadership et Management', categorie=categorie2)
    sousCate21.save()
    sousCate22 = SousCategorie(nom='Finance', categorie=categorie2)
    sousCate22.save()
    sousCate23 = SousCategorie(nom='Marketing', categorie=categorie2)
    sousCate23.save()
    sousCate24 = SousCategorie(nom='Entrepreneuriat', categorie=categorie2)
    sousCate24.save()
    sousCate25 = SousCategorie(nom='Bases du business', categorie=categorie2)
    sousCate25.save()
    sousCate26 = SousCategorie(nom='Stratégie d\'affaires', categorie=categorie2)
    sousCate26.save()

    sousCate31 = SousCategorie(nom='Développement logiciels', categorie=categorie3)
    sousCate31.save()
    sousCate32 = SousCategorie(nom='Développement mobile et web', categorie=categorie3)
    sousCate32.save()
    sousCate33 = SousCategorie(nom='Algorithmes', categorie=categorie3)
    sousCate33.save()
    sousCate34 = SousCategorie(nom='Sécurité des ordinateurs et réseaux', categorie=categorie3)
    sousCate34.save()
    sousCate35 = SousCategorie(nom='Conception et produit', categorie=categorie3)
    sousCate35.save()

    sousCate41 = SousCategorie(nom='Analyse des données', categorie=categorie4)
    sousCate41.save()
    sousCate42 = SousCategorie(nom='Apprentissage automatique', categorie=categorie4)
    sousCate42.save()
    sousCate43 = SousCategorie(nom='Probabilités et statistiques', categorie=categorie4)
    sousCate43.save()

    sousCate51 = SousCategorie(nom='Animaux et sciences vétérinaires', categorie=categorie5)
    sousCate51.save()
    sousCate52 = SousCategorie(nom='Bioinformatique', categorie=categorie5)
    sousCate52.save()
    sousCate53 = SousCategorie(nom='Biologie', categorie=categorie5)
    sousCate53.save()
    sousCate54 = SousCategorie(nom='Médécine et soins de santés', categorie=categorie5)
    sousCate54.save()
    sousCate55 = SousCategorie(nom='Nutrition', categorie=categorie5)
    sousCate55.save()

    sousCate61 = SousCategorie(nom='Mathématiques et logique', categorie=categorie6)
    sousCate61.save()

    sousCate71 = SousCategorie(nom='Développement personnel', categorie=categorie7)
    sousCate71.save()

    sousCate81 = SousCategorie(nom='Génie électrique', categorie=categorie8)
    sousCate81.save()
    sousCate82 = SousCategorie(nom='Génie mécanique', categorie=categorie8)
    sousCate82.save()
    sousCate83 = SousCategorie(nom='Chimie', categorie=categorie8)
    sousCate83.save()
    sousCate84 = SousCategorie(nom='Sciences environnementales et développement durable', categorie=categorie8)
    sousCate84.save()
    sousCate85 = SousCategorie(nom='Physique et astronomie', categorie=categorie8)
    sousCate85.save()
    sousCate86 = SousCategorie(nom='Méthodes de recherche', categorie=categorie8)
    sousCate86.save()

    sousCate91 = SousCategorie(nom='Économie', categorie=categorie9)
    sousCate91.save()
    sousCate92 = SousCategorie(nom='Enseignement', categorie=categorie9)
    sousCate92.save()
    sousCate93 = SousCategorie(nom='Gouvernance et société', categorie=categorie9)
    sousCate93.save()
    sousCate94 = SousCategorie(nom='Droit', categorie=categorie9)
    sousCate94.save()
    sousCate95 = SousCategorie(nom='Psychologie', categorie=categorie9)
    sousCate95.save()

    sousCate101 = SousCategorie(nom='Anglais', categorie=categorie10)
    sousCate101.save()
    sousCate102 = SousCategorie(nom='Autre langue', categorie=categorie10)
    sousCate102.save()