# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-28 23:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('duree', models.CharField(blank=True, max_length=10)),
                ('objectif', models.TextField(max_length=400)),
                ('langue', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='images_cours/')),
            ],
        ),
        migrations.CreateModel(
            name='DispenseCours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.Cours')),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('urlLogo', models.CharField(max_length=250)),
                ('about', models.TextField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=15)),
                ('dateNaissance', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=15)),
                ('dateNaissance', models.DateField(null=True)),
                ('photo', models.ImageField(upload_to='images_profil')),
                ('localisation', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=10)),
                ('statutProfessinnel', models.CharField(max_length=100)),
                ('niveauEtude', models.CharField(max_length=100)),
                ('statutEtudiant', models.CharField(max_length=100)),
                ('aPropos', models.TextField(max_length=250)),
                ('confidentialite', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateInscription', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.Cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.Etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('duree', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('reponse', models.CharField(max_length=100)),
                ('choix1', models.CharField(max_length=100)),
                ('choix2', models.CharField(max_length=100)),
                ('choix3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReponseSujet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=300)),
                ('dateReponse', models.DateTimeField(auto_now_add=True)),
                ('autheur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('titre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='SujetDiscussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('texte', models.TextField(max_length=300)),
                ('autheur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.Forum')),
                ('reponses', models.ManyToManyField(to='elearn.ReponseSujet')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('htmlCode', models.TextField()),
                ('duree', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus', models.TextField()),
                ('lectures', models.ManyToManyField(to='elearn.Lecture')),
                ('quizs', models.ManyToManyField(to='elearn.Quiz')),
                ('videos', models.ManyToManyField(to='elearn.Video')),
            ],
        ),
        migrations.AddField(
            model_name='reponsesujet',
            name='sujet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.SujetDiscussion'),
        ),
        migrations.AddField(
            model_name='ligne',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.Quiz'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='ressources',
            field=models.ManyToManyField(to='elearn.Ressource'),
        ),
        migrations.AddField(
            model_name='dispensecours',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.Enseignant'),
        ),
        migrations.AddField(
            model_name='cours',
            name='ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.Ecole'),
        ),
        migrations.AddField(
            model_name='cours',
            name='enseignants',
            field=models.ManyToManyField(blank=True, to='elearn.Enseignant'),
        ),
        migrations.AddField(
            model_name='cours',
            name='etudiants',
            field=models.ManyToManyField(through='elearn.Inscription', to='elearn.Etudiant'),
        ),
        migrations.AddField(
            model_name='cours',
            name='forums',
            field=models.ManyToManyField(blank=True, to='elearn.Forum'),
        ),
        migrations.AddField(
            model_name='cours',
            name='sousCategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.SousCategorie'),
        ),
        migrations.AddField(
            model_name='cours',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='elearn.Week'),
        ),
    ]
