# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
