# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-31 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0002_auto_20170529_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='nom',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cours',
            name='objectif',
            field=models.TextField(),
        ),
    ]
