# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-31 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0003_auto_20170531_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='titre',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
