# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-31 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0006_auto_20170531_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='niveau',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
