# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-10 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0009_lecture_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcript',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
